apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.name }}-config
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.name }}
    app.kubernetes.io/name: {{ .Values.metadata.name }}
type: Opaque
stringData:
  config.conf: |
    port: 4223
    http_port = 8223
    cluster_id: "test"
    streaming {
      id: "test"
      store: "file"
      dir: "/store"
    }