apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.name }}
spec:
  type: NodePort
  ports:
    - name: tcp-nats
      port: 4223
      targetPort: 4223
      protocol: TCP
    - name: http-metrics
      port: 7777
      targetPort: 7777
      protocol: TCP
  selector:
    app: {{ .Values.metadata.name }}
