apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.metadata.name }}-pvc
  namespace: {{ .Values.metadata.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: gold
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gold
  namespace: {{ .Values.metadata.namespace }}
provisioner: kubernetes.io/gce-pd
allowVolumeExpansion: true
parameters:
  type: pd-ssd