metadata:
  name: siera-kube-watch

image:
  repository: warungpintar/siera-kube-watch
  pullPolicy: IfNotPresent
  tag: v1.0.0

config:
  webhook:
    enabled: false
    url: http://webhookurl

  slack:
    enabled: false
    url: http://slackurl